/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_facebook_presto_orc_OrcReaderJNI */

#ifndef _Included_com_facebook_presto_orc_OrcReaderJNI
#define _Included_com_facebook_presto_orc_OrcReaderJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_facebook_presto_orc_OrcReaderJNI
 * Method:    processBlocks
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_facebook_presto_orc_OrcReaderJNI_processBlocks
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_facebook_presto_orc_OrcReaderJNI
 * Method:    hasNext
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_facebook_presto_orc_OrcReaderJNI_hasNext
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
